# Generated by Django 2.2.5 on 2019-10-02 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0002_auto_20191002_0656'),
        ('share', '0001_initial'),
        ('timeline', '0001_initial'),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnReactShareReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('react_date', models.DateTimeField(auto_now=True)),
                ('react_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.SnAction')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.ShareReply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SnReactShareComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('react_date', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.ShareComment')),
                ('react_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.SnAction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SnReactShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('react_post_date', models.DateTimeField(auto_now=True)),
                ('react_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reacted_type', to='general.SnAction')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_post', to='share.Share')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SnReactPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('react_post_date', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Post')),
                ('react_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.SnAction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
