# Generated by Django 2.2.5 on 2019-11-06 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('react', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snreactpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='react_post', to='timeline.Post'),
        ),
    ]
