# Generated by Django 2.2.5 on 2019-10-02 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GnOnlineStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_status', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SnActionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SnAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=20)),
                ('action_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.SnActionType')),
            ],
        ),
    ]
