# Generated by Django 2.2.5 on 2019-10-02 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_code', models.CharField(max_length=10, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('voice', models.FileField(blank=True, upload_to='')),
                ('face', models.FileField(blank=True, upload_to='')),
                ('pin', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScLoginHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(blank=True, max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('in_time', models.DateTimeField(auto_now=True)),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('online_status', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.GnOnlineStatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
