# Generated by Django 2.2.5 on 2019-10-02 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sncontentdetail',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Post'),
        ),
    ]
