# Generated by Django 2.2.5 on 2019-10-02 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0002_sncontentdetail_post'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sncontentdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ScUser'),
        ),
        migrations.AddField(
            model_name='snalbum',
            name='album_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.SnAlbumType'),
        ),
        migrations.AddField(
            model_name='snalbum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
