# Generated by Django 2.2.5 on 2019-11-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20191104_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sncontentdetail',
            name='file',
            field=models.ImageField(upload_to=''),
        ),
    ]
