# Generated by Django 2.2.5 on 2019-11-06 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20191104_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sncontentdetail',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_content', to='timeline.Post'),
        ),
    ]
