# Generated by Django 2.2.5 on 2019-11-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20191106_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sncontentdetail',
            old_name='content_type',
            new_name='content_typeo',
        ),
    ]
