# Generated by Django 2.2.5 on 2019-11-06 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20191106_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sncontentdetail',
            old_name='content_typeo',
            new_name='content_type',
        ),
    ]
