# Generated by Django 2.2.5 on 2019-11-06 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20191106_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sncontentdetail',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_content_reverse', to='timeline.Post'),
        ),
    ]
