# Generated by Django 2.2.5 on 2019-11-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20191106_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sncontentdetail',
            name='file',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
