# Generated by Django 2.2.5 on 2019-11-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20191106_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sncontentdetail',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
