# Generated by Django 2.2.5 on 2019-11-06 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20191106_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sncontentdetail',
            name='file',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
