# Generated by Django 2.2.5 on 2019-10-02 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeline', '0001_initial'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharereplycontent',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.SnContentType'),
        ),
        migrations.AddField(
            model_name='sharereplycontent',
            name='replay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.ShareReply'),
        ),
        migrations.AddField(
            model_name='sharereply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.ShareComment'),
        ),
        migrations.AddField(
            model_name='sharereply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharecommentcontent',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.ShareComment'),
        ),
        migrations.AddField(
            model_name='sharecommentcontent',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.SnContentType'),
        ),
        migrations.AddField(
            model_name='sharecomment',
            name='share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Post'),
        ),
        migrations.AddField(
            model_name='sharecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postreplycontent',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.SnContentType'),
        ),
        migrations.AddField(
            model_name='postreplycontent',
            name='replay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.PostReply'),
        ),
        migrations.AddField(
            model_name='postreply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.PostComment'),
        ),
        migrations.AddField(
            model_name='postreply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcommentcontent',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.PostComment'),
        ),
        migrations.AddField(
            model_name='postcommentcontent',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.SnContentType'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Post'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
