# Generated by Django 2.2.5 on 2019-10-02 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20191002_0656'),
        ('comment', '0002_auto_20191002_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='visibility_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.VisibilityMode'),
        ),
        migrations.AddField(
            model_name='postreply',
            name='visibility_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.VisibilityMode'),
        ),
        migrations.AddField(
            model_name='sharecomment',
            name='visibility_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.VisibilityMode'),
        ),
        migrations.AddField(
            model_name='sharereply',
            name='visibility_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.VisibilityMode'),
        ),
    ]
