# Generated by Django 2.2.5 on 2019-11-06 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visibility', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snvisibility',
            old_name='entity_id',
            new_name='content_type',
        ),
    ]
