# Generated by Django 2.2.5 on 2019-11-06 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visibility', '0002_auto_20191106_0625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snvisibility',
            old_name='value_id',
            new_name='object_id',
        ),
    ]
